# Generated by Django 3.2.6 on 2021-08-05 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fio', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('hold', models.IntegerField(default=0)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
    ]
